import plugin from "tailwindcss/plugin";

export const fullscreenTailwindPlugin = plugin(function ({ addComponents }) {
  addComponents({
    ".cui-fullscreen-container": {
      height: "100vh",
      width: "100vw",
      padding: "1rem",
      display: "flex",
      gap: "1rem",
    },
    ".cui-fullscreen-sidebar": {
      width: "264px",
      height: "100%",
      borderWidth: "1px",
      borderColor: "rgba(0, 0, 0, 0.06)",
      flexShrink: "0",
      padding: "0.67rem",
      borderRadius: "1rem",
      display: "flex",
      flexDirection: "column",
      gap: "0.5rem",
      backgroundColor: "rgba(255, 255, 255, 1)",
      transition: "width 1s ease-in-out",
      whiteSpace: "nowrap",
      overflow: "hidden",
      "&.cui-fullscreen-sidebar-closed": {
        width: "109px",
        height: "min-content",
        "& > *": {
          display: "none",
        },
        "& .cui-fullscreen-sidebar-header": {
          display: "flex",
          width: "max-content",
        },
        "& .cui-fullscreen-sidebar-title": {
          display: "none",
        },
      },
    },
    ".cui-fullscreen-sidebar-header": {
      display: "flex",
      alignItems: "center",
      justifyContent: "space-between",
      gap: "0.5rem",
    },
    ".cui-fullscreen-sidebar-header-title-icon": {
      display: "flex",
      alignItems: "center",
      gap: "0.5rem",
    },
    ".cui-fullscreen-sidebar-logo": {
      height: "1.5rem",
      width: "1.5rem",
      marginRight: "0.5rem",
    },
    ".cui-fullscreen-sidebar-title": {
      fontSize: "1.15rem",
      fontWeight: "400",
      fontStyle: "normal",
      lineHeight: "1.5rem",
      color: "rgba(0, 0, 0, 1)",
    },
    ".cui-fullscreen-sidebar-header-button": {
      display: "flex",
      alignItems: "center",
      borderRadius: "0.5rem",
      padding: "0.66rem",
      border: "1px solid rgba(0, 0, 0, 0.06)",
    },
    ".cui-fullscreen-search-input": {
      display: "flex",
      alignItems: "center",
      gap: "0.25rem",
      padding: "0.375rem 0.5rem",
      borderRadius: "0.5rem",
      border: "1px solid rgba(0, 0, 0, 0.04)",
      backgroundColor: "rgba(0, 0, 0, 0.04)",
    },
    ".cui-fullscreen-search-input-input": {
      flexGrow: "1",
      outline: "none",
      border: "none",
      backgroundColor: "transparent",
      fontSize: "0.875rem",
      fontStyle: "normal",
      fontWeight: "400",
      lineHeight: "1.25rem",
    },
    ".cui-fullscreen-new-chat-button": {
      width: "100%",
      padding: "0.5rem 1rem",
      borderRadius: "0.66rem",
      backgroundColor: "rgba(0, 0, 0, 1)",
      display: "flex",
      alignItems: "center",
      justifyContent: "left",
      gap: "0.5rem",
      "&:hover": {
        backgroundColor: "rgba(0, 0, 0, 0.8)",
      },
      color: "rgba(255, 255, 255, 1)",
    },
    ".cui-fullscreen-thread-button": {
      width: "100%",
      padding: "8px",
      textAlign: "left",
      backgroundColor: "rgba(243, 244, 246, 1)",
      borderRadius: "10px",
      outline: "1px solid rgba(0, 0, 0, 0.06)",
      textOverflow: "ellipsis",
      whiteSpace: "nowrap",
      overflow: "hidden",
      flexShrink: "0",
    },
    ".cui-fullscreen-thread-button-disabled": {
      width: "100%",
      padding: "8px",
      textAlign: "left",
      borderRadius: "10px",
      textOverflow: "ellipsis",
      whiteSpace: "nowrap",
      overflow: "hidden",
      flexShrink: "0",
      color: "rgba(0, 0, 0, 0.4)",
    },
    ".cui-fullscreen-thread-list": {
      display: "flex",
      flexDirection: "column",
      gap: "8px",
    },
    ".cui-fullscreen-thread-list-group": {
      display: "flex",
      paddingLeft: "6px",
      color: "rgba(0, 0, 0, 0.4)",
    },
    ".cui-fullscreen-thread-container": {
      flexGrow: "1",
      flexShrink: "1",
      height: "100%",
      display: "flex",
      flexDirection: "column",
      maxWidth: "800px",
      margin: "0 auto",
    },
    ".cui-fullscreen-scroll-area": {
      flexGrow: "1",
      flexShrink: "1",
      height: "100%",
      display: "flex",
      flexDirection: "column",
      overflowY: "auto",
    },
    ".cui-fullscreen-messages": {
      display: "flex",
      flexDirection: "column",
      gap: "1rem",
      padding: "1rem",
    },
    ".cui-fullscreen-message": {
      padding: "1rem",
      borderRadius: "0.375rem",
    },
    ".cui-fullscreen-message-user": {
      backgroundColor: "rgba(219, 234, 254, 1)",
      marginLeft: "2rem",
    },
    ".cui-fullscreen-message-assistant": {
      backgroundColor: "rgba(243, 244, 246, 1)",
      marginRight: "2rem",
    },
    ".cui-fullscreen-composer": {
      display: "flex",
      alignItems: "center",
      gap: "0.67rem",
      padding: "0.67rem",
      border: "1px solid rgba(0, 0, 0, 0.06)",
      borderRadius: "1rem",
      overflow: "hidden",
    },
    ".cui-fullscreen-composer-input": {
      flexGrow: "1",
      padding: "0",
      resize: "none",
      height: "1.5em",
      outline: "none",
      overflow: "hidden",
      color: "rgba(0, 0, 0, 1)",
    },
    ".cui-fullscreen-composer-button": {
      padding: "1rem",
      backgroundColor: "rgba(0, 0, 0, 1)",
      color: "white",
      borderRadius: "1rem",
      border: "rgba(0, 0, 0, 0.10)",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
    },
  });
});
