import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  docsSidebar: [
    "index",
    {
      type: "category",
      label: "Quickstart",
      link: {
        type: "doc",
        id: "quickstart/index",
      },
      items: ["quickstart/python-fastapi", "quickstart/nextjs"],
    },
    {
      type: "category",
      label: "Concepts",
      items: [{ type: "autogenerated", dirName: "concepts" }],
    },
    {
      type: "category",
      label: "Guides",
      items: [{ type: "autogenerated", dirName: "guides" }],
    },
    {
      type: "category",
      label: "Tutorials",
      items: [{ type: "autogenerated", dirName: "tutorials" }],
    },
  ],
  referenceSidebar: [
    {
      type: "category",
      label: "JS API Reference",
      items: [
        {
          type: "autogenerated",
          dirName: "reference/js",
        },
      ],
    },
  ],
};

export default sidebars;
